src/Luny/SiteBundle/Entity/GenParam.php
<?php

namespace Luny\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Entity\GenParam
 *
 * @ORM\Entity(repositoryClass="GenParamRepository")
 * @ORM\Table(name="general_parameters", indexes={@ORM\Index(name="name", columns={"name"})})
 */
class GenParam
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", unique=true, length=200)
     */
    protected $name;

    /**
     * @var string HTML/JavaScript код счётчика посещений
     * @ORM\Column(type="text", nullable=true)
     */
    protected $counter;

    /**
     * @var string E-mail адрес обратной связи
     * @ORM\Column(type="string", length=100)
     */
    protected $email;
    
    /**
     * @var string Телефон(ы) для связи
     * @ORM\Column(type="string", nullable=true)
     */
    protected $phone;
    
    /**
     * @var bool true, если на сайте ведутся технические работы
     * @ORM\Column(type="bool", nullable=true)
     */
    protected $handling = true;


    /**
     * Set name
     *
     * @param string $name
     * @return GenParam
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * For SonataAdmin ACL
     *
     * @return string 
     */
    public function getId()
    {
        return $this->name;
    }

    /**
     * Set counter
     *
     * @param string $counter
     * @return GenParam
     */
    public function setCounter($counter)
    {
        $this->counter = $counter;

        return $this;
    }

    /**
     * Get counter
     *
     * @return string 
     */
    public function getCounter()
    {
        return $this->counter;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return GenParam
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return GenParam
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }
    
    public function __toString()
    {
        return 'Настройки';
    }
    

    /**
     * Set handling
     *
     * @param bool $handling
     * @return GenParam
     */
    public function setHandling($handling)
    {
        $this->handling = $handling;

        return $this;
    }

    /**
     * Get handling
     *
     * @return bool 
     */
    public function getHandling()
    {
        return $this->handling;
    }
}

src/Luny/SiteBundle/Resources/views/Admin/edit.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends 'SonataAdminBundle:CRUD:base_edit.html.twig' %}

{% block stylesheets %}
        {{ parent() }}
                <style>
                    .select2-choices, textarea, input {
                      width: 35em !important;
                    }
                </style>
{% endblock %}

src/Luny/SiteBundle/Resources/views/Admin/field_tree_down.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}

    {% spaceless %}
        {% if object.parent.children[object.parent.children|length - 1].id != object.id %}
            <a href="{{ path('page_tree_down', {'page_id': object.id}) }}">
                <img src="{{ asset('image/admin/arrow_down.png') }}" alt="{% trans %}Вниз{% endtrans %}" />
            </a>
        {% endif %}
    {% endspaceless %}
{% endblock %}

src/Luny/SiteBundle/Resources/views/Admin/field_tree_up.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}

    {% spaceless %}
        {% if object.parent.children[0].id != object.id %}
            <a href="{{ path('page_tree_up', {'page_id': object.id}) }}">
                <img src="{{ asset('image/admin/arrow_up.png') }}" alt="{% trans %}Вверх{% endtrans %}" />
            </a>
        {% endif %}
    {% endspaceless %}
{% endblock %}

src/Luny/SiteBundle/Resources/views/Admin/sonata_admin_base_layout.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/ckeditor/ckeditor.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/mod-synctranslit.js') }}" type="text/javascript"></script>
    
    <script>
        $(document).ready(function(){
            $('[data-origin=page_name]').syncTranslit({destination: 'page_path'});
        });
    </script>
{% endblock %}
    
{% block stylesheets %}
        {{ parent() }}
                 <style>
                    #genparam {
                        display: list-item;
                        margin-top: 3px;
                        list-style-image: url({{ asset('image/admin/properties.png') }}) !important;
                    }
                </style>
{% endblock %}
                
{% block side_bar_after_nav %}
                        <ul id="genparam">
                            <li>
                                <a href="{{ path('admin_luny_site_genparam_edit', {'id': 'luny'}) }}">Общие настройки</a>
                            </li>
                        </ul>
 {% endblock %}
                
                